// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  newsSidebar: [
    "news/2026-04-13-ai-news",
  ],
  knowledgeSidebar: [
    {
      type: "category",
      label: "知识体系",
      items: [{ type: "autogenerated", dirName: "knowledge" }],
    },
    {
      type: "category",
      label: "教程与指南",
      items: [{ type: "autogenerated", dirName: "guides-and-tutorials" }],
    },
    {
      type: "category",
      label: "模型评测",
      items: [{ type: "autogenerated", dirName: "model-reviews" }],
    },
    {
      type: "category",
      label: "工具与框架",
      items: [{ type: "autogenerated", dirName: "tools-and-frameworks" }],
    },
    {
      type: "category",
      label: "方法论",
      items: [{ type: "autogenerated", dirName: "methods" }],
    },
    {
      type: "category",
      label: "资源",
      items: [{ type: "autogenerated", dirName: "resources" }],
    },
  ],
};

module.exports = sidebars;
